# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import ferry_pb2 as ferry__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ferry_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FerryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestData = channel.unary_unary(
            "/ferry.FerryService/IngestData",
            request_serializer=ferry__pb2.IngestRequest.SerializeToString,
            response_deserializer=ferry__pb2.IngestResponse.FromString,
            _registered_method=True,
        )
        self.GetObservability = channel.unary_unary(
            "/ferry.FerryService/GetObservability",
            request_serializer=ferry__pb2.ObservabilityRequest.SerializeToString,
            response_deserializer=ferry__pb2.ObservabilityResponse.FromString,
            _registered_method=True,
        )


class FerryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetObservability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FerryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "IngestData": grpc.unary_unary_rpc_method_handler(
            servicer.IngestData,
            request_deserializer=ferry__pb2.IngestRequest.FromString,
            response_serializer=ferry__pb2.IngestResponse.SerializeToString,
        ),
        "GetObservability": grpc.unary_unary_rpc_method_handler(
            servicer.GetObservability,
            request_deserializer=ferry__pb2.ObservabilityRequest.FromString,
            response_serializer=ferry__pb2.ObservabilityResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ferry.FerryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ferry.FerryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class FerryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ferry.FerryService/IngestData",
            ferry__pb2.IngestRequest.SerializeToString,
            ferry__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetObservability(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ferry.FerryService/GetObservability",
            ferry__pb2.ObservabilityRequest.SerializeToString,
            ferry__pb2.ObservabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
