# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/ferry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/ferry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/ferry.proto\x12\x05\x66\x65rry\"r\n\rIngestRequest\x12\x10\n\x08identity\x18\x01 \x01(\t\x12\x12\n\nsource_uri\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x65stination_uri\x18\x03 \x01(\t\x12\"\n\tresources\x18\x04 \x03(\x0b\x32\x0f.ferry.Resource\"\xb0\x01\n\x08Resource\x12\x19\n\x11source_table_name\x18\x01 \x01(\t\x12\x1e\n\x16\x64\x65stination_table_name\x18\x02 \x01(\t\x12(\n\x0c\x63olumn_rules\x18\x03 \x01(\x0b\x32\x12.ferry.ColumnRules\x12?\n\x18write_disposition_config\x18\x04 \x01(\x0b\x32\x1d.ferry.WriteDispositionConfig\"F\n\x0b\x43olumnRules\x12\x17\n\x0f\x65xclude_columns\x18\x01 \x03(\t\x12\x1e\n\x16pseudonymizing_columns\x18\x02 \x03(\t\"&\n\x16WriteDispositionConfig\x12\x0c\n\x04type\x18\x01 \x01(\t\"H\n\x0eIngestResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rpipeline_name\x18\x03 \x01(\t\"(\n\x14ObservabilityRequest\x12\x10\n\x08identity\x18\x01 \x01(\t\"8\n\x15ObservabilityResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07metrics\x18\x02 \x01(\t2\x98\x01\n\x0c\x46\x65rryService\x12\x39\n\nIngestData\x12\x14.ferry.IngestRequest\x1a\x15.ferry.IngestResponse\x12M\n\x10GetObservability\x12\x1b.ferry.ObservabilityRequest\x1a\x1c.ferry.ObservabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.ferry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTREQUEST']._serialized_start=29
  _globals['_INGESTREQUEST']._serialized_end=143
  _globals['_RESOURCE']._serialized_start=146
  _globals['_RESOURCE']._serialized_end=322
  _globals['_COLUMNRULES']._serialized_start=324
  _globals['_COLUMNRULES']._serialized_end=394
  _globals['_WRITEDISPOSITIONCONFIG']._serialized_start=396
  _globals['_WRITEDISPOSITIONCONFIG']._serialized_end=434
  _globals['_INGESTRESPONSE']._serialized_start=436
  _globals['_INGESTRESPONSE']._serialized_end=508
  _globals['_OBSERVABILITYREQUEST']._serialized_start=510
  _globals['_OBSERVABILITYREQUEST']._serialized_end=550
  _globals['_OBSERVABILITYRESPONSE']._serialized_start=552
  _globals['_OBSERVABILITYRESPONSE']._serialized_end=608
  _globals['_FERRYSERVICE']._serialized_start=611
  _globals['_FERRYSERVICE']._serialized_end=763
# @@protoc_insertion_point(module_scope)
