source:
  postgres:
    username: postgres_user
    password: postgres_password
    host: postgres_host
    port: 5432
    database: postgres_db

destination:
  clickhouse:
    username: clickhouse_user
    password: clickhouse_password
    host: clickhouse_host
    port: 9000
    database: clickhouse_db
    dataset_name: clickhouse_dataset

tables:
  table1:
    incremental_key: id1
  table2:
    incremental_key: id2