repos:
  - repo: local
    hooks:
      - id: detect-special-characters
        name: Detect Special Characters in API Keys
        entry: bash .git/hooks/detect-special-characters.sh
        language: system
        files: '.*'  # Scan all files
        pass_filenames: true
