# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ferry_pb2 as ferry__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ferry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataLoaderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadData = channel.unary_unary(
                '/ferry.DataLoader/LoadData',
                request_serializer=ferry__pb2.LoadDataRequest.SerializeToString,
                response_deserializer=ferry__pb2.LoadDataResponse.FromString,
                _registered_method=True)


class DataLoaderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataLoaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadData': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadData,
                    request_deserializer=ferry__pb2.LoadDataRequest.FromString,
                    response_serializer=ferry__pb2.LoadDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ferry.DataLoader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ferry.DataLoader', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataLoader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ferry.DataLoader/LoadData',
            ferry__pb2.LoadDataRequest.SerializeToString,
            ferry__pb2.LoadDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
