# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ferry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ferry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x65rry.proto\x12\x05\x66\x65rry\"\x8f\x01\n\x0fLoadDataRequest\x12\x12\n\nsource_uri\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65stination_uri\x18\x02 \x01(\t\x12\x19\n\x11source_table_name\x18\x03 \x01(\t\x12\x1e\n\x16\x64\x65stination_table_name\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x61taset_name\x18\x05 \x01(\t\"D\n\x10LoadDataResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\t2I\n\nDataLoader\x12;\n\x08LoadData\x12\x16.ferry.LoadDataRequest\x1a\x17.ferry.LoadDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ferry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADDATAREQUEST']._serialized_start=23
  _globals['_LOADDATAREQUEST']._serialized_end=166
  _globals['_LOADDATARESPONSE']._serialized_start=168
  _globals['_LOADDATARESPONSE']._serialized_end=236
  _globals['_DATALOADER']._serialized_start=238
  _globals['_DATALOADER']._serialized_end=311
# @@protoc_insertion_point(module_scope)
