name: Gitleaks Secret Scan

on:
  push:
    branches:
      - feature/grpc
  pull_request:
    branches:
      - feature/grpc

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  
      
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with: 