name: Secret Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml
          fail: true
          scan-recent: "true"


      - name: Check for secrets
        run: |
          if git diff --quiet; then
            echo " No secrets found!"
          else
            echo " Secrets detected! Commit rejected."
            exit 1
          fi

      