name: Gitleaks Secret Scan

on:
  push:
    branches:
      - feature/grpc
  pull_request:
    branches:
      - feature/grpc

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only fetch the latest commit
      
      - name: Run Gitleaks on latest commit
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          ./gitleaks detect --redact --no-git --source=.
