name: Secret Scan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:  # Allows manual trigger

jobs:
  scan-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: gitleaks/gitleaks-action@v2